import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Check for certificate files (generated by ASP.NET Core)
const certPath = path.resolve(__dirname, 'certificates')
const keyFilePath = path.join(certPath, 'localhost.key')
const certFilePath = path.join(certPath, 'localhost.pem')

const httpsConfig = fs.existsSync(keyFilePath) && fs.existsSync(certFilePath)
  ? {
      key: fs.readFileSync(keyFilePath),
      cert: fs.readFileSync(certFilePath),
    }
  : undefined

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    port: 55327,
    https: httpsConfig,
    strictPort: true,
  },
})
